"""three_automation_modules

Revision ID: 3352b5e45e19
Revises: d8e4f2a619ab
Create Date: 2026-08-26 12:18:28.878997
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '3352b5e45e19'
down_revision: Union[str, None] = 'd8e4f2a619ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reply_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope_key', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope_key')
    )
    op.create_table('touch_reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_key', sa.String(length=120), nullable=False),
    sa.Column('owner_key', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('reserved_at', sa.String(length=40), nullable=False),
    sa.Column('expires_at', sa.String(length=40), nullable=False),
    sa.Column('confirmed_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_key')
    )
    op.create_table('wakeup_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sop_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sop_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sop_id'], ['sop_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sop_id', 'version')
    )
    op.create_table('automation_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('inbox_binding_id', sa.Integer(), nullable=True),
    sa.Column('conversation_state_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('virtual_now', sa.String(length=40), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('memory', sa.JSON(), nullable=False),
    sa.Column('controls', sa.JSON(), nullable=False),
    sa.Column('batch_started_at', sa.String(length=40), nullable=True),
    sa.Column('due_at', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['conversation_state_id'], ['conversation_states.id'], ),
    sa.ForeignKeyConstraint(['inbox_binding_id'], ['inbox_bindings.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_sessions_due_at'), 'automation_sessions', ['due_at'], unique=False)
    op.create_table('sync_conversation_cursors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('conversation_state_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['conversation_state_id'], ['conversation_states.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['sync_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'conversation_state_id')
    )
    op.create_table('automation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=20), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=False),
    sa.Column('decision', sa.JSON(), nullable=False),
    sa.Column('trace', sa.JSON(), nullable=False),
    sa.Column('error_code', sa.String(length=120), nullable=True),
    sa.Column('lease_token', sa.String(length=80), nullable=True),
    sa.Column('lease_until', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('completed_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['automation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_automation_runs_session_id'), 'automation_runs', ['session_id'], unique=False)
    op.create_index(op.f('ix_automation_runs_status'), 'automation_runs', ['status'], unique=False)
    op.create_table('rehearsal_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('sop_version_id', sa.Integer(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('enrolled_at', sa.String(length=40), nullable=False),
    sa.Column('expires_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['automation_sessions.id'], ),
    sa.ForeignKeyConstraint(['sop_version_id'], ['sop_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'sop_version_id', 'generation')
    )
    op.create_table('rehearsal_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('node_key', sa.String(length=80), nullable=False),
    sa.Column('predecessor_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=True),
    sa.Column('confirmed_at', sa.String(length=40), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['rehearsal_enrollments.id'], ),
    sa.ForeignKeyConstraint(['predecessor_id'], ['rehearsal_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'node_key')
    )
    op.create_index(op.f('ix_rehearsal_jobs_scheduled_at'), 'rehearsal_jobs', ['scheduled_at'], unique=False)
    op.create_table('silence_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('policy_snapshot', sa.JSON(), nullable=False),
    sa.Column('customer_at', sa.String(length=40), nullable=False),
    sa.Column('reply_at', sa.String(length=40), nullable=False),
    sa.Column('due_at', sa.String(length=40), nullable=False),
    sa.Column('expires_at', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('evaluation_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['wakeup_policies.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['automation_runs.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['automation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'generation')
    )
    op.create_index(op.f('ix_silence_cycles_due_at'), 'silence_cycles', ['due_at'], unique=False)
    op.create_index(op.f('ix_silence_cycles_session_id'), 'silence_cycles', ['session_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_silence_cycles_session_id'), table_name='silence_cycles')
    op.drop_index(op.f('ix_silence_cycles_due_at'), table_name='silence_cycles')
    op.drop_table('silence_cycles')
    op.drop_index(op.f('ix_rehearsal_jobs_scheduled_at'), table_name='rehearsal_jobs')
    op.drop_table('rehearsal_jobs')
    op.drop_table('rehearsal_enrollments')
    op.drop_index(op.f('ix_automation_runs_status'), table_name='automation_runs')
    op.drop_index(op.f('ix_automation_runs_session_id'), table_name='automation_runs')
    op.drop_table('automation_runs')
    op.drop_table('sync_conversation_cursors')
    op.drop_index(op.f('ix_automation_sessions_due_at'), table_name='automation_sessions')
    op.drop_table('automation_sessions')
    op.drop_table('sop_versions')
    op.drop_table('wakeup_policies')
    op.drop_table('touch_reservations')
    op.drop_table('reply_policies')
    # ### end Alembic commands ###
