"""initial schema

Revision ID: 6bf4f33f2eee
Revises: 
Create Date: 2026-08-16 19:38:29.242469
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '6bf4f33f2eee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('ai_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=500), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('worker_heartbeats',
    sa.Column('worker_id', sa.String(length=100), nullable=False),
    sa.Column('last_seen_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('worker_id')
    )
    op.create_table('chatwoot_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_api_token', sa.LargeBinary(), nullable=True),
    sa.Column('token_last4', sa.String(length=4), nullable=True),
    sa.Column('connection_key', sa.String(length=96), nullable=False),
    sa.Column('webhook_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_tested_at', sa.String(length=40), nullable=True),
    sa.Column('last_webhook_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id'),
    sa.UniqueConstraint('connection_key'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('chatwoot_contact_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'chatwoot_contact_id')
    )
    op.create_table('inbox_bindings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('chatwoot_inbox_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('channel_type', sa.String(length=100), nullable=False),
    sa.Column('ai_enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('last_synced_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'chatwoot_inbox_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.String(length=40), nullable=False),
    sa.Column('revoked_at', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_session_hash'), 'sessions', ['session_hash'], unique=True)
    op.create_table('conversation_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('inbox_binding_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('chatwoot_conversation_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('can_reply', sa.Boolean(), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('effective_ai_state', sa.String(length=50), nullable=False),
    sa.Column('effective_state_reason', sa.String(length=200), nullable=False),
    sa.Column('last_message', sa.Text(), nullable=False),
    sa.Column('last_customer_message_at', sa.String(length=40), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['inbox_binding_id'], ['inbox_bindings.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'chatwoot_conversation_id')
    )
    op.create_table('user_inbox_scopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('inbox_binding_id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['inbox_binding_id'], ['inbox_bindings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'inbox_binding_id')
    )
    op.create_table('webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=80), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('inbox_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.String(length=200), nullable=False),
    sa.Column('idempotency_key', sa.String(length=500), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.String(length=40), nullable=False),
    sa.Column('lease_owner', sa.String(length=100), nullable=True),
    sa.Column('lease_expires_at', sa.String(length=40), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('received_at', sa.String(length=40), nullable=False),
    sa.Column('processed_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['chatwoot_connections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_webhook_pending', 'webhook_events', ['status', 'available_at'], unique=False)
    op.create_table('message_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_state_id', sa.Integer(), nullable=False),
    sa.Column('chatwoot_message_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=30), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['conversation_state_id'], ['conversation_states.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_state_id', 'chatwoot_message_id')
    )
    op.create_table('ai_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_state_id', sa.Integer(), nullable=False),
    sa.Column('trigger_message_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('completed_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['conversation_state_id'], ['conversation_states.id'], ),
    sa.ForeignKeyConstraint(['trigger_message_id'], ['message_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trigger_message_id')
    )
    op.create_table('outbound_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_state_id', sa.Integer(), nullable=False),
    sa.Column('ai_run_id', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chatwoot_message_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('submitted_at', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['ai_run_id'], ['ai_runs.id'], ),
    sa.ForeignKeyConstraint(['conversation_state_id'], ['conversation_states.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_outbound_messages_chatwoot_message_id'), 'outbound_messages', ['chatwoot_message_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbound_messages_chatwoot_message_id'), table_name='outbound_messages')
    op.drop_table('outbound_messages')
    op.drop_table('ai_runs')
    op.drop_table('message_events')
    op.drop_index('ix_webhook_pending', table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_table('user_inbox_scopes')
    op.drop_table('conversation_states')
    op.drop_index(op.f('ix_sessions_session_hash'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('inbox_bindings')
    op.drop_table('contacts')
    op.drop_table('chatwoot_connections')
    op.drop_table('worker_heartbeats')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tenants')
    op.drop_table('app_settings')
    # ### end Alembic commands ###

