import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Plus, RefreshCw, Save, Trash2 } from 'lucide-react';
import { api } from '../api';
import { Modal, PageHeader, Toggle } from '../components';
import './advisor-assignment.css';

type Rule = {id:string; name:string; enabled:boolean; event:string; priority:number; inbox_ids:number[]; routes:string[]; minimum_people:number|null; minimum_days:number|null; action:'assign'|'handoff'|'notify'; strategy:'fixed'|'round_robin'; agent_ids:number[]};
type Config = {enabled:boolean; advisors:{agent_id:number; accepting:boolean}[]; rules:Rule[]; fallback_agent_id:number|null};
type Data = {config:Config; events:Record<string,string>; agents:{id:number; name:string; availability:string; inbox_ids:number[]}[]; routes:{id:string;name:string}[]; inboxes:{id:number;name:string}[]};
type RecordItem = {id:number;conversation_id:number;customer:string;event:string;rule:string;agent:string;status:string;error:string|null;created_at:string};
const actions = {assign:'分配负责人，AI继续',handoff:'转人工并分配',notify:'只通知'};
const statuses:Record<string,string> = {pending:'等待同步',retry:'重试中',processing:'同步中',synced:'已同步',unassigned:'待分配',unmatched:'未命中规则',failed:'同步失败',cancelled:'已取消'};

export default function AdvisorAssignment() {
  const qc = useQueryClient();
  const query = useQuery({queryKey:['advisor-assignment'],queryFn:()=>api<Data>('/advisor-assignment')});
  const [draft,setDraft] = useState<Config|null>(null);
  const [tab,setTab] = useState('rules');
  const [editing,setEditing] = useState<Rule|null>(null);
  const [notice,setNotice] = useState('');
  const [page,setPage] = useState(1);
  const [status,setStatus] = useState('');
  const config = draft ?? query.data?.config;
  const records = useQuery({queryKey:['assignment-records',page,status],queryFn:()=>api<{items:RecordItem[];total:number}>(`/advisor-assignment/records?page=${page}&status=${status}`),enabled:tab==='records',refetchInterval:10000});
  const save = useMutation({mutationFn:()=>api<{config:Config}>('/advisor-assignment',{method:'PUT',body:JSON.stringify(config)}),onSuccess:r=>{qc.setQueryData<Data>(['advisor-assignment'],old=>old?{...old,config:r.config}:old);setDraft(null);setNotice('已保存');}});
  const sync = useMutation({mutationFn:()=>api('/settings/chatwoot/sync',{method:'POST'}),onSuccess:()=>{qc.invalidateQueries({queryKey:['advisor-assignment']});setNotice('顾问列表已同步');}});
  const retry = useMutation({mutationFn:(id:number)=>api(`/advisor-assignment/records/${id}/retry`,{method:'POST'}),onSuccess:()=>qc.invalidateQueries({queryKey:['assignment-records']})});
  const error = query.error || save.error || sync.error || records.error || retry.error;
  if (!config || !query.data) return <div className="page-content">{error?.message || '正在读取顾问分配…'}</div>;
  const data = query.data;
  const patch = (value:Partial<Config>)=>{setDraft({...config,...value});setNotice('');};
  const add = ()=>setEditing({id:crypto.randomUUID(),name:'',enabled:true,event:'handoff.created',priority:0,inbox_ids:[],routes:[],minimum_people:null,minimum_days:null,action:'handoff',strategy:'fixed',agent_ids:[]});
  const updateRule = ()=>{if(!editing)return;patch({rules:config.rules.some(r=>r.id===editing.id)?config.rules.map(r=>r.id===editing.id?editing:r):[...config.rules,editing]});setEditing(null);};
  return <div className="page-content assignment-page">
    <PageHeader title="顾问分配" description="" actions={<><label className="assignment-toggle"><Toggle checked={config.enabled} onChange={enabled=>patch({enabled})} label="启用自动分配"/>自动分配</label><button className="primary-button" disabled={!draft||save.isPending} onClick={()=>save.mutate()}><Save size={16}/>保存{draft?'更改':''}</button></>}/>
    <div className="handoff-tabs">{[['rules','分配规则'],['advisors','顾问'],['records','分配记录']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
    {error?<div className="login-error" role="alert">{error.message}</div>:null}{notice?<p role="status">{notice}</p>:null}
    {tab==='advisors'?<section className="panel"><header className="panel-header"><h2>顾问列表</h2><button className="secondary-button" disabled={sync.isPending} onClick={()=>sync.mutate()}><RefreshCw size={15}/>同步Chatwoot</button></header><div className="responsive-table"><table><thead><tr><th>顾问</th><th>收件箱</th><th>参与分配</th><th>接单状态</th></tr></thead><tbody>{data.agents.map(agent=>{const selected=config.advisors.find(a=>a.agent_id===agent.id);return <tr key={agent.id}><td>{agent.name}</td><td>{agent.inbox_ids.map(id=>data.inboxes.find(i=>i.id===id)?.name??id).join('、')||'无'}</td><td><input aria-label={`参与分配 ${agent.name}`} type="checkbox" checked={!!selected} onChange={e=>patch({advisors:e.target.checked?[...config.advisors,{agent_id:agent.id,accepting:true}]:config.advisors.filter(a=>a.agent_id!==agent.id)})}/></td><td><select aria-label={`${agent.name}接单状态`} disabled={!selected} value={selected?.accepting?'on':'off'} onChange={e=>patch({advisors:config.advisors.map(a=>a.agent_id===agent.id?{...a,accepting:e.target.value==='on'}:a)})}><option value="on">接单</option><option value="off">停接</option></select></td></tr>})}</tbody></table></div>{!data.agents.length?<p className="assignment-empty">尚无顾问，请先同步Chatwoot。</p>:null}<div className="assignment-fallback"><label>无人可分配时<select value={config.fallback_agent_id??''} onChange={e=>patch({fallback_agent_id:e.target.value?Number(e.target.value):null})}><option value="">进入待分配</option>{data.agents.filter(a=>config.advisors.some(s=>s.agent_id===a.id)).map(a=><option key={a.id} value={a.id}>交给{a.name}</option>)}</select></label></div></section>:null}
    {tab==='rules'?<section className="panel"><header className="panel-header"><span>优先级高的规则先执行；已有负责人时保留归属。</span><button className="secondary-button" onClick={add}><Plus size={15}/>添加规则</button></header><div className="responsive-table"><table><thead><tr><th>启用</th><th>规则</th><th>事件</th><th>动作</th><th>顾问</th><th>优先级</th><th/></tr></thead><tbody>{[...config.rules].sort((a,b)=>b.priority-a.priority).map(rule=><tr key={rule.id}><td><Toggle checked={rule.enabled} label={`启用 ${rule.name}`} onChange={enabled=>patch({rules:config.rules.map(r=>r.id===rule.id?{...r,enabled}:r)})}/></td><td><button className="text-button" onClick={()=>setEditing(structuredClone(rule))}>{rule.name}</button></td><td>{data.events[rule.event]}</td><td>{actions[rule.action]}</td><td>{rule.agent_ids.map(id=>data.agents.find(a=>a.id===id)?.name??id).join('、')}<small>{rule.strategy==='fixed'?'固定分配':'轮流均分'}</small></td><td>{rule.priority}</td><td><button className="icon-button" aria-label={`删除 ${rule.name}`} onClick={()=>patch({rules:config.rules.filter(r=>r.id!==rule.id)})}><Trash2 size={15}/></button></td></tr>)}</tbody></table></div>{!config.rules.length?<p className="assignment-empty">添加事件规则，选择负责顾问。</p>:null}</section>:null}
    {tab==='records'?<section className="panel"><header className="panel-header"><select aria-label="筛选分配状态" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">全部状态</option>{Object.entries(statuses).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select><button className="secondary-button" onClick={()=>records.refetch()}><RefreshCw size={15}/>刷新</button></header><div className="responsive-table"><table><thead><tr><th>时间</th><th>客户</th><th>事件</th><th>规则</th><th>顾问</th><th>状态</th><th/></tr></thead><tbody>{records.data?.items.map(r=><tr key={r.id}><td>{new Date(r.created_at).toLocaleString()}</td><td><a href={`#/conversations?conversation=${r.conversation_id}`}>{r.customer||`会话 #${r.conversation_id}`}</a></td><td>{r.event}</td><td>{r.rule||'—'}</td><td>{r.agent}</td><td>{statuses[r.status]||r.status}{r.error?<small className="assignment-error">{r.error}</small>:null}</td><td>{['failed','unassigned'].includes(r.status)?<button className="text-button" disabled={retry.isPending} onClick={()=>retry.mutate(r.id)}>重试</button>:null}</td></tr>)}</tbody></table></div>{!records.data?.items.length?<p className="assignment-empty">暂无分配记录</p>:null}<footer className="table-pagination"><span>共{records.data?.total??0}条</span><div><button className="secondary-button" disabled={page===1} onClick={()=>setPage(page-1)}>上一页</button><span>{page}</span><button className="secondary-button" disabled={page*30>=(records.data?.total??0)} onClick={()=>setPage(page+1)}>下一页</button></div></footer></section>:null}
    <Modal open={!!editing} title={config.rules.some(r=>r.id===editing?.id)?'编辑分配规则':'添加分配规则'} description="" onClose={()=>setEditing(null)} footer={<><button className="secondary-button" onClick={()=>setEditing(null)}>取消</button><button className="primary-button" disabled={!editing?.name.trim()||!editing.agent_ids.length||(editing.event==='customer.profile'&&!editing.minimum_days&&!editing.minimum_people)} onClick={updateRule}>确定</button></>}>
      {editing?<div className="form-stack assignment-rule-form"><label>规则名称<input value={editing.name} maxLength={120} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><div className="assignment-form-row"><label>触发事件<select value={editing.event} onChange={e=>setEditing({...editing,event:e.target.value})}>{Object.entries(data.events).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>优先级<input type="number" min={0} max={999} value={editing.priority} onChange={e=>setEditing({...editing,priority:Number(e.target.value)})}/></label></div><div className="assignment-form-row"><label>线路<select value={editing.routes[0]??''} onChange={e=>setEditing({...editing,routes:e.target.value?[e.target.value]:[]})}><option value="">全部线路</option>{data.routes.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>收件箱<select value={editing.inbox_ids[0]??''} onChange={e=>setEditing({...editing,inbox_ids:e.target.value?[Number(e.target.value)]:[]})}><option value="">全部收件箱</option>{data.inboxes.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label></div><div className="assignment-form-row"><label>人数至少<input type="number" min={1} placeholder="不限" value={editing.minimum_people??''} onChange={e=>setEditing({...editing,minimum_people:e.target.value?Number(e.target.value):null})}/></label><label>客户要求的行程天数至少<input type="number" min={1} placeholder="不限" value={editing.minimum_days??''} onChange={e=>setEditing({...editing,minimum_days:e.target.value?Number(e.target.value):null})}/></label></div><label>执行动作<select value={editing.action} onChange={e=>setEditing({...editing,action:e.target.value as Rule['action']})}>{Object.entries(actions).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>分配方式<select value={editing.strategy} onChange={e=>setEditing({...editing,strategy:e.target.value as Rule['strategy'],agent_ids:editing.agent_ids.slice(0,1)})}><option value="fixed">固定顾问</option><option value="round_robin">多位顾问轮流均分</option></select></label><fieldset className="assignment-advisor-options"><legend>顾问</legend>{data.agents.filter(a=>config.advisors.some(s=>s.agent_id===a.id)).map(a=><label key={a.id}><input type={editing.strategy==='fixed'?'radio':'checkbox'} name="rule-advisor" checked={editing.agent_ids.includes(a.id)} onChange={e=>setEditing({...editing,agent_ids:editing.strategy==='fixed'?[a.id]:e.target.checked?[...editing.agent_ids,a.id]:editing.agent_ids.filter(id=>id!==a.id)})}/>{a.name}</label>)}{!config.advisors.length?<span>请先在顾问页选择参与分配的顾问。</span>:null}</fieldset></div>:null}
    </Modal>
  </div>;
}
