import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertTriangle, CheckCircle2, ChevronLeft, ChevronRight, Clock3, RefreshCw, Search, UserCheck } from 'lucide-react';
import { api, ApiError } from '../api';
import { Avatar, Badge, EmptyState, Modal, PageHeader } from '../components';
import { useAuth } from '../auth';

interface Handoff { id: number; conversation_id: number; customer_name: string; inbox: string; reason_code: string; reason_detail: string; priority: string; status: string; assignee?: string; assignee_user_id?: number; assignment_pending?: boolean; assignment_target_agent_id?: number; sla_due_at?: string; created_at: string; version: number; labels: string[]; }
interface UserItem { id: number; display_name: string; role: string; active: boolean; chatwoot_agent_id?: number; }
const tabs = [{ id: 'pending', label: '待接管' }, { id: 'claimed', label: '处理中' }, { id: 'completed', label: '已完成' }];
const waitText = (date: string) => { const seconds = Math.max(0, (Date.now() - new Date(date).getTime()) / 1000); return seconds > 3600 ? `${Math.floor(seconds / 3600)}小时` : `${Math.floor(seconds / 60)}分钟`; };

export default function Handoff({ notify }: { notify: (message: string) => void }) {
  const [tab, setTab] = useState('pending'); const [query, setQuery] = useState(''); const [page, setPage] = useState(1); const [selected, setSelected] = useState<Handoff | null>(null); const [targetUser, setTargetUser] = useState<number | null>(null);
  const { user } = useAuth(); const qc = useQueryClient();
  const pageSize = 10;
  const tasks = useQuery({ queryKey: ['handoffs', tab, query, page], queryFn: () => api<{ items: Handoff[]; counts: Record<string, number>; total: number; page: number }>(`/handoffs?status=${tab}&q=${encodeURIComponent(query)}&page=${page}&page_size=${pageSize}`), refetchInterval: 10000 });
  const users = useQuery({ queryKey: ['users'], queryFn: () => api<{ items: UserItem[] }>('/users'), enabled: user?.roles[0] === 'admin' });
  const refresh = () => qc.invalidateQueries({ queryKey: ['handoffs'] });
  const action = useMutation({ mutationFn: ({ path, body }: { path: string; body: object }) => api<Handoff>(path, { method: 'POST', body: JSON.stringify(body) }), onSuccess: (data) => { setSelected(null); refresh(); notify(`会话 #${data.conversation_id} 已更新`); }, onError: (error: ApiError) => { refresh(); notify(error.message); } });
  const claim = (item: Handoff) => action.mutate({ path: `/handoffs/${item.id}/claim`, body: { version: item.version } });
  const complete = (item: Handoff) => action.mutate({ path: `/handoffs/${item.id}/complete`, body: { version: item.version } });
  const restore = (item: Handoff) => action.mutate({ path: `/handoffs/${item.id}/restore-ai`, body: { version: item.version } });
  const totalPages = Math.max(1, Math.ceil((tasks.data?.total ?? 0) / pageSize));
  return <div className="page-content handoff-page"><PageHeader eyebrow="HUMAN HANDOFF" title="人工接管队列" description="集中处理 AI 升级的复杂咨询；领取会同步 Chatwoot 坐席，完成后 AI 仍保持暂停。" actions={<button className="secondary-button" onClick={refresh}><RefreshCw size={16} />刷新队列</button>} />
    <section className="handoff-tabs">{tabs.map((item) => <button key={item.id} className={tab === item.id ? 'active' : ''} onClick={() => { setTab(item.id); setPage(1); }}><span>{item.label}</span><strong>{tasks.data?.counts[item.id] ?? 0}</strong></button>)}</section>
    <section className="table-toolbar"><div className="toolbar-search"><Search size={16} /><input value={query} onChange={(e) => { setQuery(e.target.value); setPage(1); }} placeholder="搜索客户、会话或接管原因" /></div><span className="toolbar-result">共 {tasks.data?.total ?? 0} 个任务</span></section>
    <section className="panel table-panel">{tasks.isLoading ? <EmptyState type="loading" title="正在读取队列" description="" /> : !tasks.data?.items.length ? <EmptyState title="当前队列为空" description="没有符合条件的人工接管任务。" /> : <div className="responsive-table"><table><thead><tr><th>优先级</th><th>客户 / 会话</th><th>接管原因</th><th>等待时间</th><th>分配</th><th className="align-right">操作</th></tr></thead><tbody>{tasks.data.items.map((item, index) => <tr key={item.id} className={item.priority === 'P1' ? 'priority-row' : ''}><td><span className={`priority priority-${item.priority.toLowerCase()}`}>{item.priority === 'P1' ? <AlertTriangle size={14} /> : null}{item.priority}</span></td><td><div className="customer-cell"><Avatar initials={item.customer_name.slice(0, 2)} tone={index} /><div><strong>{item.customer_name}</strong><span>{item.inbox} · #{item.conversation_id}</span></div></div></td><td><Badge tone={item.reason_code.includes('error') ? 'red' : 'amber'}>{item.reason_code}</Badge><p className="reason-copy">{item.reason_detail || '未填写说明'}</p></td><td><div className={item.sla_due_at && new Date(item.sla_due_at) < new Date() ? 'wait-time overdue' : 'wait-time'}><Clock3 size={14} />{waitText(item.created_at)}</div></td><td><strong className="table-main">{item.assignee || '未分配'}</strong></td><td className="align-right"><div className="row-action-group">{item.assignment_pending ? <button className="secondary-button compact" disabled={action.isPending} onClick={() => action.mutate({ path: `/handoffs/${item.id}/reconcile-assignment`, body: { version: item.version } })}>核对分配</button> : item.status === 'pending' ? <><button className="primary-button compact" onClick={() => claim(item)}><UserCheck size={15} />领取</button>{user?.roles[0] !== 'agent' ? <button className="secondary-button compact" onClick={() => { setSelected(item); setTargetUser(null); }}>改派</button> : null}</> : item.status === 'claimed' ? <button className="secondary-button compact" onClick={() => complete(item)}><CheckCircle2 size={15} />完成</button> : user?.roles[0] !== 'agent' ? <button className="secondary-button compact" onClick={() => restore(item)}>恢复 AI</button> : <Badge>等待主管恢复</Badge>}</div></td></tr>)}</tbody></table></div>}</section>
    {tasks.data?.total ? <footer className="table-pagination"><span>第 {page} / {totalPages} 页</span><div><button className="icon-button" aria-label="上一页" disabled={page <= 1} onClick={() => setPage((value) => Math.max(1, value - 1))}><ChevronLeft size={17} /></button><button className="icon-button" aria-label="下一页" disabled={page >= totalPages} onClick={() => setPage((value) => Math.min(totalPages, value + 1))}><ChevronRight size={17} /></button></div></footer> : null}
    <Modal open={Boolean(selected)} title="改派人工任务" description="目标用户必须已绑定 Chatwoot Agent。" onClose={() => setSelected(null)} footer={<><button className="secondary-button" onClick={() => setSelected(null)}>取消</button><button className="primary-button" disabled={!targetUser || action.isPending} onClick={() => selected && targetUser && action.mutate({ path: `/handoffs/${selected.id}/assign`, body: { version: selected.version, user_id: targetUser } })}>确认改派</button></>}><div className="form-stack"><label>平台客服<select value={targetUser ?? ''} onChange={(e) => setTargetUser(Number(e.target.value) || null)}><option value="">请选择</option>{users.data?.items.filter((x) => x.active && x.chatwoot_agent_id).map((x) => <option key={x.id} value={x.id}>{x.display_name} · {x.role}</option>)}</select></label></div></Modal>
  </div>;
}
