import { ArrowRight } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { ApiError } from '../api';
import { Badge, EmptyState } from '../components';
import '../automation.css';
import { RuntimeDetails } from '../DeliveryDetails';
import { deliveryStates, type RuntimeEvidence } from '../delivery';

type Presentation = { type?: string; route_variant?: string; route_ids?: string[]; criteria?: string[]; recommendation?: string; material_keys?: string[]; evidence_refs?: string[]; topics?: string[]; routes?: { route_variant?: string; name?: string; selection_title?: string; days?: number; includes_everest?: boolean; price_per_person?: number | null; dimensions?: Record<string, { value?: string; evidence_refs?: string[] }> }[]; details?: { topic?: string; text?: string }[] };
export interface RunRecord { id: number; session_id: number; module: string; status: string; generation: number; error_code?: string; created_at: string; decision: { action?: string; reply?: string; branch?: string; slots?: Record<string, unknown>; evidence_refs?: string[]; handoff_reason?: string; safety_flags?: string[]; wakeup_action?: string; materials?: { name: string }[]; material_keys?: string[]; presentations?: Presentation[] }; trace: RuntimeEvidence['trace'] & { total_ms?: number; evidence_ms?: number; model_ms?: number; validation_ms?: number; request_count?: number; model_http_request_count?: number; model_input_tokens?: number; model_output_tokens?: number; environment?: string; effective_model?: string; engine_version?: string; engine_release_id?: string; route_knowledge_versions?: Record<string,string>; input_tokens?: number; output_tokens?: number } }
export const statusLabel = (value: string) => deliveryStates[value]?.label ?? ({ already_provided: '此前已提供', active: '进行中', pending: '等待处理', processing: '处理中', completed: '已完成', failed: '失败', blocked: '已阻断', discarded: '已废弃', candidate: '待评估', queued: '评估中', draft: '草稿', deferred: '已延后', excluded: '不联系', handoff_suggested: '建议人工', simulated_delivered: '模拟送达', submitted: '已提交', submission_unknown: '发送结果待核对', attention_required: '需要人工核对', cancelled: '已取消', scheduled: '待执行', waiting_dependency: '等待前序', running: '运行中', paused: '已暂停', stopped: '已结束', expired: '已过期', skipped: '已跳过' }[value] ?? value);
export function DemoUnavailable() { return <EmptyState type="permission" title="公开 Demo 未开放模型演练" description="" />; }
export function Failure({ error }: { error: unknown }) { return error ? <div className="automation-error" role="alert">{(error as ApiError).code === 'version_conflict' ? '配置已被更新，请刷新后重试。' : (error as Error).message}</div> : null; }
const presentationLabels: Record<string, string> = { route_comparison: "线路比较", route_details: "线路详情", itinerary: "行程展示", route_materials: "线路资料", suggestions: "下一步建议" };
const criterionLabels: Record<string, string> = { duration: "天数", pace: "节奏", hotel: "住宿", price: "价格", highlights: "亮点", itinerary: "行程", vehicle: "用车", oxygen: "供氧", departure: "出发时间" };
function RunPresentations({ items }: { items?: Presentation[] }) {
  if (!items?.length) return null;
  return <section className="automation-presentation-summary"><strong>结构化展示</strong>{items.map((item, index) => <article key={`${item.type ?? 'presentation'}-${index}`}><header><b>{presentationLabels[item.type ?? ''] ?? item.type ?? '展示内容'}</b>{item.recommendation ? <Badge tone="green">推荐 {item.recommendation}</Badge> : null}</header>{item.route_ids?.length ? <p>{item.route_ids.join(' · ')}</p> : null}{item.route_variant ? <p>{item.route_variant}{item.topics?.length ? ` · ${item.topics.join('、')}` : ''}</p> : null}{item.criteria?.length ? <div className="automation-presentation-tags">{item.criteria.map(value => <span key={value}>{criterionLabels[value] ?? value}</span>)}</div> : null}{item.routes?.map(route => <div className="automation-presentation-route" key={route.route_variant}><b>{route.name || route.route_variant}</b>{route.days ? <small>{route.days}天</small> : null}{Object.entries(route.dimensions ?? {}).slice(0, 4).map(([key, value]) => <p key={key}><span>{criterionLabels[key] ?? key}</span>{value.value || '—'}</p>)}</div>)}{item.details?.map(detail => <p key={detail.topic}>{detail.topic ? `${detail.topic}?` : ''}{detail.text}</p>)}</article>)}</section>;
}
export function RunList({ rows }: { rows: RunRecord[] }) {
  const navigate = useNavigate();
  return !rows.length ? <EmptyState title="暂无运行记录" description="" /> : <div className="automation-run-list">{rows.map(row => <details key={row.id}><summary><span className="run-number">#{row.id}</span><Badge tone={row.status === 'completed' ? 'green' : row.status === 'failed' ? 'red' : 'neutral'}>{statusLabel(row.status)}</Badge><span className="run-preview">{row.decision.reply || row.error_code || row.decision.handoff_reason || (row.decision.action === 'no_action' ? row.decision.wakeup_action === 'defer' ? '延后评估' : '无需回复' : '等待决策')}</span><small>{row.trace.total_ms != null ? `${(row.trace.total_ms / 1000).toFixed(2)}s` : ''}</small></summary><div className="run-expanded"><RuntimeDetails run={row} /><p>{row.decision.reply}</p><RunPresentations items={row.decision.presentations} /><dl><dt>决策</dt><dd>{row.decision.wakeup_action || row.decision.action || '-'}</dd><dt>阻断原因</dt><dd>{row.error_code || row.decision.handoff_reason || '-'}</dd><dt>事实引用</dt><dd>{row.decision.evidence_refs?.join(' / ') || '-'}</dd><dt>校验标记</dt><dd>{row.decision.safety_flags?.join(' / ') || '-'}</dd><dt>阶段耗时</dt><dd>资料 {row.trace.evidence_ms ?? 0}ms · 模型 {row.trace.model_ms ?? 0}ms · 校验 {row.trace.validation_ms ?? 0}ms</dd><dt>素材</dt><dd>{row.decision.materials?.map(x => x.name).join(' / ') || row.decision.material_keys?.join(' / ') || '无'}</dd><dt>实际模型请求 / Token</dt><dd>{row.trace.model_http_request_count ?? '未记录'} / {(row.trace.model_input_tokens ?? 0) + (row.trace.model_output_tokens ?? 0)}</dd><dt>环境 / 引擎 / 模型</dt><dd>{row.trace.environment ?? '未记录'} / {row.trace.engine_version ?? '未记录'} / {row.trace.effective_model ?? '未记录'}</dd><dt>发布 / 知识版本</dt><dd>{row.trace.engine_release_id ?? '未记录'} / {Object.values(row.trace.route_knowledge_versions ?? {}).join(' / ') || '未记录'}</dd></dl><button className="secondary-button compact" onClick={() => navigate(`/playground?session=${row.session_id}`)}>查看演练<ArrowRight size={14} /></button></div></details>)}</div>;
}
